name: WalRus tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  autotests:
    name: Run tests

    runs-on: ubuntu-latest
    container:
      image: postgres:14.4
      options: -u 1001 --tmpfs=/pgtmpfs -e PGDATA=/pgtmpfs

    steps:
      - uses: actions/checkout@v2

      - name: Run Test
        run: |
          bin/installcheck
