name: WALRUS tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  autotests:
    name: Run tests

    runs-on: ubuntu-latest
    container:
      image: postgres:14.4
      options: --tmpfs=/pgtmpfs -e PGDATA=/pgtmpfs

    steps:
      - uses: actions/checkout@v2

      - name: Run Test
        run: |
          chown -R postgres /__w/walrus/walrus
          su postgres -c 'bin/installcheck'

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: regression.out
          path: regression.out
          retention-days: 7
